### ISSUE TITLE
Update /e/OS devices

### ISSUE THREAD

**Issue by HemanthJabalpuri** [Customrombay/database#26]
https://community.e.foundation/t/list-new-devices-to-be-added-to-the-list-of-supported-devices-on-e-os-t-part-ii/54628

I don't know if any other devices added between that list and your repo.

**Comment by PiotrZPL** [comment]
The database is unfortunately out of sync with the /e/OS repos. That is because they have a lot of duplicate entries in their .yaml files, which is not supported by this file format and causes dart's YAML interpreter to crash. This was also the case in the [lineage_wiki repo](https://github.com/LineageOS/lineage_wiki) before I fixed it with [this commit](https://github.com/LineageOS/lineage_wiki/commit/97360174e8eab338d7b848db4b626ef0ce8cd72e).

For now, I do not have the time to create a pull request in [their repository](https://gitlab.e.foundation/e/documentation/user/-/tree/master/htdocs/_data/devices) and adjust my script. But it will happen, one day.

**Comment by PiotrZPL** [comment]
@HemanthJabalpuri The support for automatic syncing with /e/OS was fixed in [63278d0](https://github.com/Customrombay/database/commit/63278d0a902c10a07f0b1928a34514dc925c5a15). Thank you for this issue. Closing...
